### PR TITLE
Switch modifier order

### PR DESCRIPTION
**Pull request by naszam**
- Minor: consider switching modifier order

### CODE REVIEW

**Comment by gbalabasquer** [comment]
What would be the reason for this change?

**Comment by naszam** [comment]
Checked with @brianmcmichael about this:
- [Balancer Finance | ConsenSys Diligence](https://consensys.net/diligence/audits/2020/05/balancer-finance/#switch-modifier-order-in-bpool)

Opened the PR for discussion.

**Comment by gbalabasquer** [comment]
Ok, yeah I don't think is necessary. Even in the example what is the problem of calling `logs` and then the `lock` modifier. Reentrancy will be shutdown anyway and the tx will revert. There will be something extra in the trace though, but don't think it is a problem.
I mean if we would be doing a new contract I think we can follow that convention but I wouldn't touch an existing and deployed contract due this change, excepting we are planning to do several changes to it.

**Comment by brianmcmichael** [comment]
Same comment as https://github.com/makerdao/dss-vest/pull/43#issuecomment-992945025

**Review by brianmcmichael — APPROVED** [review]

**Review by gbalabasquer — APPROVED** [review]

**Pull request merged**
